### ISSUE TITLE
extension.cssConverter not found

### ISSUE THREAD

**Issue by nchristopherteague** [Lakkanna/css-converter#14]
After installing, I get extension.cssConverter not found. Also, if I go to the settings and enable/disable auto format, I get cssConverter.autoFormat is not a registered  configuration

**Comment by Lakkanna** [comment]
Sorry for the delay, now this issue is fixed in version v0.1.3, please do confirm by installing new version is an extension is activating or not, if it's working fine please close issue.

**Comment by Lakkanna** [comment]
I am closing this issue if you got the same error please reopen the issue.
